language: julia

julia:
  - 0.7
  - 1.0

os:
  - linux
  - osx

notifications:
  email:
    - maxim.bouton@gmail.com

# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("POMDPModels"; coverage=true)'

after_success:
#  - julia --project -e 'import Pkg; Pkg.add("Documenter"); include("docs/make.jl")'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
